# Generated by Django 2.2.2 on 2019-06-09 18:48

import corp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corp', '0002_remove_item_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False, verbose_name='ID автора')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия автора')),
                ('middlename', models.CharField(max_length=100, verbose_name='Отчество автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', models.AutoField(primary_key=True, serialize=False, verbose_name='ID темы')),
                ('theme', models.CharField(max_length=100, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема текста',
                'verbose_name_plural': 'Темы текстов',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='theme',
        ),
        migrations.AddField(
            model_name='header',
            name='id_user',
            field=models.ForeignKey(db_column='id', default=0, on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='ID юзера'),
        ),
        migrations.AddField(
            model_name='header',
            name='visibility',
            field=models.CharField(default=1, max_length=1, verbose_name='Видимость корпуса'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_corp',
        ),
        migrations.AddField(
            model_name='item',
            name='id_corp',
            field=models.ManyToManyField(db_column='id_corp', to='corp.Header'),
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id_addon', models.AutoField(primary_key=True, serialize=False, verbose_name='ID аддона')),
                ('name', models.CharField(max_length=100, verbose_name='Название аддона')),
                ('description', models.CharField(max_length=255, verbose_name='Краткое описание аддона')),
                ('file_manual', models.FileField(upload_to=corp.models.addon_manual_path, verbose_name='Инструкция')),
                ('file_description', models.FileField(upload_to=corp.models.addon_descr_path, verbose_name='Описание файлов')),
                ('file_example', models.FileField(upload_to=corp.models.addon_example_path, verbose_name='Примеры использования')),
                ('id_user', models.ForeignKey(db_column='id', on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='ID юзера')),
            ],
            options={
                'verbose_name': 'Аддон',
                'verbose_name_plural': 'Аддоны',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='id_theme',
            field=models.ForeignKey(db_column='id_theme', default=0, on_delete=None, to='corp.Theme', verbose_name='ID темы'),
        ),
    ]
