# Generated by Django 2.2.2 on 2019-06-11 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0003_auto_20190609_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='id_user',
            field=models.ForeignKey(db_column='id', on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='ID юзера'),
        ),
    ]
