# Generated by Django 2.2.2 on 2019-06-11 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0005_auto_20190611_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='ID юзера'),
        ),
    ]
