# Generated by Django 2.2.2 on 2019-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0006_auto_20190611_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.AddField(
            model_name='item',
            name='id_author',
            field=models.ForeignKey(db_column='id_author', default=0, on_delete=None, to='corp.Author', verbose_name='Автор текста'),
        ),
    ]
